package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"errors"

	graph "github.com/sheelendar196/go-projects/graphql-project/graph/generated"
	"github.com/sheelendar196/go-projects/graphql-project/graph/model"
)

// CreateEmployee is the resolver for the createEmployee field.
func (r *mutationResolver) CreateEmployee(ctx context.Context, input model.NewEmployee) (*model.Employee, error) {
	employee := getEmployeeFromInput(input)
	err := r.EmployeeProcessor.SaveEmployee(ctx, employee)
	if err != nil {
		return nil, errors.New("employee details not saved into db")
	}
	return &employee, nil
}

// UpdateEmployee is the resolver for the updateEmployee field.
func (r *mutationResolver) UpdateEmployee(ctx context.Context, input model.NewEmployee) (*model.Employee, error) {
	employee := getEmployeeFromInput(input)
	return r.EmployeeProcessor.UpdateEmployee(ctx, employee)
}

// GetEmployee is the resolver for the getEmployee field.
func (r *queryResolver) GetEmployee(ctx context.Context, empID string) (*model.Employee, error) {
	return r.EmployeeProcessor.GetEmployee(ctx, empID)
}

// DeleteEmployee is the resolver for the deleteEmployee field.
func (r *queryResolver) DeleteEmployee(ctx context.Context, empID string) (*model.Employee, error) {
	return r.EmployeeProcessor.DeleteEmployee(ctx, empID)
}

// GetEmployeeList is the resolver for the getEmployeeList field.
func (r *queryResolver) GetEmployeeList(ctx context.Context) ([]*model.Employee, error) {
	return r.EmployeeProcessor.GetEmployeeList(ctx)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.

func getEmployeeFromInput(input model.NewEmployee) model.Employee {
	employee := model.Employee{
		Name:       input.Name,
		EmpID:      input.EmpID,
		Address:    input.Address,
		IsActive:   input.IsActive,
		ManagerID:  input.ManagerID,
		Mobile:     input.Mobile,
		Department: input.Department,
		Email:      input.Email,
	}
	return employee
}
