// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	EmpID      string  `json:"empID"`
	Mobile     *string `json:"mobile,omitempty"`
	Email      *string `json:"email,omitempty"`
	Address    *string `json:"address,omitempty"`
	ManagerID  *string `json:"managerID,omitempty"`
	IsActive   *bool   `json:"isActive,omitempty"`
	Department *string `json:"department,omitempty"`
}

type Mutation struct {
}

type NewEmployee struct {
	Name       string  `json:"name"`
	EmpID      string  `json:"empID"`
	Mobile     *string `json:"mobile,omitempty"`
	Email      *string `json:"email,omitempty"`
	Address    *string `json:"address,omitempty"`
	ManagerID  *string `json:"managerID,omitempty"`
	IsActive   *bool   `json:"isActive,omitempty"`
	Department *string `json:"department,omitempty"`
}

type Query struct {
}
